### ISSUE TITLE
Why do not you add a cocoapods？

### ISSUE THREAD

**Issue by coderyi** [kasketis/netfox#1]
Why do not you add a cocoapods or a Carthage？

That will make people more convenient to use

**Comment by vCrespoP** [comment]
+1

I see you two guys are jumping from each one to the other with this framework haha. 

Nice work, keep it up.

**Comment by coderyi** [comment]
vCrespoP,you are also very funny,haha

**Comment by vCrespoP** [comment]
https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by kasketis** [comment]
Done. Please verify :)

**Comment by vCrespoP** [comment]
Nope sorry. Remember you have to make public what you want to be visible outside your framework.

Modify this so the protocol can be adopted when subclassing Alamofire's manager:

``` public class NFXProtocol : NSURLProtocol  ```

Notes: 
- All pods seem to start with capital letter, just in case you want to modify that as well.
- Remember to update the podspec when you bump the version of the framework and commit&push it to the repo!

Come on, we're near!

**Comment by kasketis** [comment]
Could you please check it now? :D

**Comment by pavelserbajlo** [comment]
works for me, thanks for taking care of this so quickly!

**Comment by kasketis** [comment]
Nice! I'm closing it. If you face any other problems please open a new one or reopen this ;)
