### ISSUE TITLE
Add Travis CI?

### ISSUE THREAD

**Issue by Janglinator** [kasketis/netfox#101]
Would you mind if I added a Travis config to this repo?  I'll configure it to build against Swift 3.2 and 4.0, to make sure we don't cause build issues for anybody again.

**Comment by kasketis** [comment]
Of course not, please proceed 👍

**Comment by Janglinator** [comment]
@kasketis Would you mind going to https://travis-ci.org/kasketis/netfox quick and getting us set up?  I can do the work, I just need permission to do so in Travis

**Comment by kasketis** [comment]
Ready! Please check

**Comment by Janglinator** [comment]
Well... That was fast!  Push a config...

**Comment by kasketis** [comment]
:) let me know if you need any help 👍

**Comment by Janglinator** [comment]
Shouldn't be too hard, just had a few facepalms.  3rd time should be the charm.
