### ISSUE TITLE
Facebook Audience Network requests can't be logged

### ISSUE THREAD

**Issue by mhillebrand** [kasketis/netfox#103]
I love Netfox, but I'm unable to see requests made to *.facebook.com from Facebook's FAN SDK:

https://origincache.facebook.com/developers/resources/?id=FBAudienceNetwork-4.26.1.zip

It's a dynamic framework, so I'm not sure how their HTTP requests are being made exactly. Any ideas?

Thanks,
Matt

**Comment by mhillebrand** [comment]
Ah, it's because the FAN framework relies in WKWebView. 😢 

I did some Googling and found some interesting workarounds:

- https://github.com/Yeatse/NSURLProtocol-WebKitSupport
- https://medium.com/glose-team/custom-scheme-handling-and-wkwebview-in-ios-11-72bc5113e344

**Comment by Janglinator** [comment]
This seems like a lot more testing needs to happen

**Comment by Janglinator** [comment]
I added a WKWebView to the sample project.  We can use this for testing the proposed solution.  I haven't gotten a chance to write an actual fix yet though

**Comment by vGubriienko** [comment]
Closing this as already make task in project for that https://github.com/kasketis/netfox/projects/1#card-76856365
