### ISSUE TITLE
Possible reject when submit to itunes connect ?

### ISSUE THREAD

**Issue by wasappi** [kasketis/netfox#104]
Was there any case of rejects from Apple when using this (wonderful btw) library in production code ?

**Comment by Janglinator** [comment]
We haven't had any issues.  We do ship the code into production, but that's only so we can use it in testflight.  Once we release the version, Netfox is then disabled for that version, so Apple testers never "see" the Netfox window when testing, but the codebase is still packaged in there.

**Comment by felipeflorencio** [comment]
Looks like there's no problem at all, I will close this question, but if any problem shows up we reopen if need.
