### ISSUE TITLE
http traffic statistic is not exactly

### ISSUE THREAD

**Issue by Beyond-Chao** [kasketis/netfox#105]
`self.requestBodyLength = data.count
totalResponseSize += model.responseBodyLength! `

that data is fetched from `session!.dataTask(with: req as URLRequest, completionHandler: {data, response, error in}`

if HTTP response header has field: content-encoding:gzip, the real transmit data size is small than completionHandler`s data. So totalResponseSize is not exactly, Is that right？

I want statistic total traffic for iOS APP, the total traffic is eqaul to totalRequestSize + totalResponseSize (Data out + Data in), Is that right？

Thanks in advance for you answer!

**Comment by Janglinator** [comment]
I'd have to do some testing to be positive.

Use something like Charles Proxy, which would give you the raw packet, and measure it's length (using a text editor character counter), and compare that to the packet length iOS gives you
