### ISSUE TITLE
DebugMan - iOS debugger tool for Swift

### ISSUE THREAD

**Issue by liman123** [kasketis/netfox#106]
Hi, I released [DebugMan](https://github.com/liman123/DebugMan) - iOS debugger tool for Swift
Welcome to use! 😃 thanks!
@jasoncabot @Abeansits @chrispix @jasonlagaac @freak4pc

**Comment by freak4pc** [comment]
I’m a bit xonfused - is this just a tool that does the same in swift ? If so, why is it an Issue in this repo ? 🤔🤔🤔

**Comment by kasketis** [comment]
Spam
