### ISSUE TITLE
Add Droar reference in README?

### ISSUE THREAD

**Issue by Janglinator** [kasketis/netfox#113]
Recently(ish), we wrote a debugging "drawer" utility we named [Droar](https://github.com/myriadmobile/Droar).  We're ready to release (we'll always be adding features, so it will never be "done"), but I still need to do some work on the README (add a .gif, more thorough usage, etc).

The idea of Droar is simple:  We wanted to be able to quickly add modular configuration to our app (switching between http environments, switching on/off mock data, etc), but it always ended up being more work than it's worth.  Droar solves this issue by making configuration switches and buttons [super easy](https://github.com/myriadmobile/netfox-Droar/blob/master/netfox-Droar/Classes/netfox-Droar.swift)!

We love Netfox, and we even wrote a [Droar plugin](https://github.com/myriadmobile/netfox-Droar) for it.  They compliment each other very well.

We want to start getting some community involvement in Droar, so we can make it even better with everyone's suggestions.  Would we be able to add a tiny reference at the bottom of Netfox's README, under an "Integrations" section that would link to our Droar plugin?

I'll make a PR for you to approve and merge, but as I'm finishing up Droar's README, we wanted to get permission ahead of time.

Thanks!

**Comment by kasketis** [comment]
This sounds interesting! Good luck 👍 
Regarding your request, you can add an "Integrations" section above "Other" section on README. Add the link to the Droar plugin along with a line that describes what Droad does.
