### ISSUE TITLE
Version is hardcoded

### ISSUE THREAD

**Issue by Abeansits** [kasketis/netfox#122]
It should be read from the info plist instead.

https://github.com/kasketis/netfox/blob/dc67d5d06c15c48798be2b58fe6ca35e1ce8445f/netfox/Core/NFX.swift#L15

**Comment by Janglinator** [comment]
I added a solution.

Currently, the official version is the version in the podspec, and I think I'd like to keep it that way.  The Git tag and everything depends on this number.

I added a bit of code to pull that podspec version number on a Cocoapods installation, but I'm not quite sure how this would work for Carthage.

Let me know if you have a better idea!  😄
