### ISSUE TITLE
Integration with Alamofire in iOS 9 causes RTO

### ISSUE THREAD

**Issue by edopelawi** [kasketis/netfox#124]
The title says it all. I tried to configure Netfox 1.11.1 with Alamofire 4.6.0 using the [workarounds here](https://github.com/kasketis/netfox/blob/master/Workarounds.md), with exception of `NSURLSessionConfiguration`'s change from `defaultSessionConfiguration()` to `default` in Swift 4.

This issue is not apparent when I try it in iOS 9 and higher, or when I didn't call the `NFX.sharedInstance().start` in iOS 9. The issue still persist when I tried newer version of Alamofire.

Does anyone have this issue too? Any help would be appreciated! 😁

**Comment by edopelawi** [comment]
Wait, turns out the issue gone when I downgraded to 1.11.0.

**Comment by sveinnv** [comment]
I'm having the same issues, downgrading to 1.11.0 fixes it.

**Comment by teemu-rossi** [comment]
I faced the same issue using netfox 1.11.1 and AFNetworking 3.1.0 on iOS 11.4.1.

**Comment by Janglinator** [comment]
Would you be able to try out release 1.12.1 (just do a pod update) and let me know if this fixes it?

**Comment by teemu-rossi** [comment]
My issue still remains even with 1.12.1.
`[Error] POST '(null)' (0): Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x1d4e58a80 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://***/, NSErrorFailingURLKey=https://***/, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}`

**Comment by Janglinator** [comment]
Thank you, I'll take a look.

I'm surprised iOS 9 is still being supported  😆

**Comment by RolandasRazma** [comment]
has nothing to do with iOS 9, we have same timeout issue (iOS10 min target) with netfox above v1.10.5

**Comment by volatilegg** [comment]
Hi, do we have any news on this one, I got the same issue, could this be because of add SSL pinning support? 🤔 
 
https://github.com/kasketis/netfox/commit/fb1e48d2b3d7720757de23bc095a9577a70d8b84

**Comment by iamqk** [comment]
swizzleDefault() in NFXHelper.swift combined with Alamofire? cause iOS 9 simulator request time out

**Comment by LittleYuz** [comment]
> Hi, do we have any news on this one, I got the same issue, could this be because of add SSL pinning support? 🤔
> 
> [fb1e48d](https://github.com/kasketis/netfox/commit/fb1e48d2b3d7720757de23bc095a9577a70d8b84)

I think so, there is no problem with the HTTP request. I deleted `public func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)` in `NFXProtocol.swift`, then HTTPS request won't time out

**Comment by vGubriienko** [comment]
Anybody still have the issue on latest version?

**Comment by vGubriienko** [comment]
Closed due to inactivity

**Comment by mikechouto** [comment]
@vGubriienko Hi, I'm still having this issue on newest version, upload will timeout on newest version, i've tried to use older version `1.10.3` and it works, seems there's still something wrong.
