### ISSUE TITLE
Exporting as HAR file

### ISSUE THREAD

**Issue by Janglinator** [kasketis/netfox#127]
Looking in the email, I received the following under the request section:

```
-- Body --

Too long to show. If you want to see it, please tap the following button
```

We should maybe let exporting show the full body  :)

**Comment by felipeflorencio** [comment]
It's not that clear for me, it's a bug about did not exported the full log, or like the payload had for example a image as string and this usually lead to a very big payload that sometimes is hard to debug using a proxy for example, just to check the situation.

**Comment by Janglinator** [comment]
I get something like this:

```** INFO **
[URL] 
https://***/api/v2/sites/135/dead-animal-image

[Method] 
POST

[Status] 
204

[Request date] 
2018-07-09 20:44:39 +0000

[Response date] 
2018-07-09 20:44:47 +0000

[Time interval] 
8.48193

[Timeout] 
60.0

[Cache policy] 
UseProtocolCachePolicy



** REQUEST **
-- Headers --

[Platform-Version] 
11.4

[Content-Length] 
2139836

[App-Version] 
1.3.0

[Accept] 
application/json

[Module] 
pen_rider

[App-Name] 
com.***.internal

[Content-Type] 
multipart/form-data; boundary=alamofire.boundary.29533272ec9d78bf

[App-Installation-Id] 
***

[User-Agent] 
***/1.3.0 (com.***.internal; build:1; iOS 11.4.0) Alamofire/4.5.1

[Platform-Name] 
ios

[Accept-Language] 
en-US;q=1.0

[Authorization] 
Token ***

[Accept-Encoding] 
gzip;q=1.0, compress;q=0.5


-- Body --

Too long to show. If you want to see it, please tap the following button


** RESPONSE **
-- Headers --

[Cache-Control] 
no-cache

[x-xss-protection] 
1; mode=block

[Strict-Transport-Security] 
max-age=31104000

[x-frame-options] 
SAMEORIGIN

[Server] 
nginx

[Date] 
Mon, 09 Jul 2018 20:44:47 GMT

[x-content-type-options] 
nosniff


-- Body --

Response body is empty


logged via netfox - [https://github.com/kasketis/netfox]```

**Comment by felipeflorencio** [comment]
Good to know I will take a look and see if fits and update here tnx

**Comment by vGubriienko** [comment]
@tivadarmolitorisz the link is broken now and I close the issue.

**Comment by tivadarmolitorisz** [comment]
@vGubriienko hey, you can close it, it's up to you but it was forked under our company account! So you can still check it [here](https://github.com/team-supercharge/netfox/tree/HAR-support)

**Comment by vGubriienko** [comment]
> @vGubriienko hey, you can close it, it's up to you but it was forked under our company account! So you can still check it [here](https://github.com/team-supercharge/netfox/tree/HAR-support)

Thanks, will check it later.

**Comment by vGubriienko** [comment]
Moved to project.
