### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by hardikdevios** [kasketis/netfox#128]
is it possible you to develop same thing in Android or do you have similar lib in who can fullfill some what of this lib ?

**Comment by ugurcmk** [comment]
You can use https://github.com/jgilfelt/chuck

**Comment by felipeflorencio** [comment]
These looks good:
https://github.com/jainsahab/AndroidSnooper
https://github.com/isacan/Andzu

**Comment by Janglinator** [comment]
Thanks for the suggestions guys!

**Comment by aatifansari** [comment]
all the libraries listed above intercept user created HTTP request using OkHttp.. is there a way to log third-party API calls made from my application

**Comment by daviddmr** [comment]
I suggest you to 

> all the libraries listed above intercept user created HTTP request using OkHttp.. is there a way to log third-party API calls made from my application

I suggest you use a Web Debugging Proxy like Charles or Proxyman for that.

**Comment by aatifansari** [comment]
Thanks everyone for your help... Though I cannot find any suitable library for the same but found a work-around to achieve the same.
1st scenario - User created HTTP request made through library like okhttp can be intercepted using various libraries listed above.
2nd scenario - In my case all other request were being fired from inside a webview. So I  have intercept the request using WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request).
IMP - You cannot intercept the response using this but can return a custom response if required the same.
3rd scenario - In scenario where you are required to log response also. I have a suggestion -
Intercept the request using above listed method then transform and make the call on your end using okhttp library and then return the response formatted as WebResourceResponse. In this way you can log the response also.

Hope it help someone
