### ISSUE TITLE
Allow export to iCloud

### ISSUE THREAD

**Issue by PetrPrazak** [kasketis/netfox#133]
Hi, 
when using Netfox on simulator, it's not possible to export the log, b/c there is no Mail app.
Could it be possible to add the option to export logs to iCloud, to be accessible by Files.app?
Thanks.

**Comment by felipeflorencio** [comment]
It's something that can be add, but the easiest way for do this and even to any other app running on simulator is use the tool https://simpholders.com/, you can easy try on trial period and buy latter if think that worth, I use and it's a must have tool for developer even more important when handle database and want to download and check

**Comment by PetrPrazak** [comment]
Hmm, the app doesn't work with the XCode 9.4.1 :(

**Comment by felipeflorencio** [comment]
https://simpholders.com/3/

;)

**Comment by PetrPrazak** [comment]
I'm not lucky using this application.
Anyway, I have created a PR for sharing: https://github.com/kasketis/netfox/pull/134

**Comment by Janglinator** [comment]
I've merged in your PR.  Let me know if there's any other ideas you had!
