### ISSUE TITLE
tcp support?

### ISSUE THREAD

**Issue by hashg** [kasketis/netfox#14]

**Comment by kasketis** [comment]
Hello! Could you please give me some more info? What you want to log?

**Comment by hashg** [comment]
What if my requests are not through http or https. FTP or pure tcp connections?
<img width="995" alt="screen shot 2015-11-28 at 7 16 21 pm" src="https://cloud.githubusercontent.com/assets/309076/11455186/eca69866-9604-11e5-862d-729cf4476bda.png">

**Comment by kasketis** [comment]
Hello again @hashg ,
Pure TCP requests cannot be supported through current implementation.
If you want to monitor such connections maybe this can help you http://stackoverflow.com/questions/19977759/network-activity-monitoring-on-iphone
