### ISSUE TITLE
Not logging Network calls for KSDeffered Network Library

### ISSUE THREAD

**Issue by SKSwain1985** [kasketis/netfox#141]
I am using KSDeffered Library for my network API calls , Please let me know how can I integrate with my Project

**Comment by Janglinator** [comment]
Hmm I've never used KSDeffered, but looking into it, it doesn't appear to be a networking library, but rather just an asynchronous management library.  How are you making your actual network calls?

The usage of Netfox should be automatic, are you not seeing any logs?  Would you mind sharing a bit of code around how you're making network requests in conglomeration with KSDeffered?

**Comment by SKSwain1985** [comment]
Hi Janglinator , Thats a quick replay, i have finally got it worked. Need to set the session protocol class as per the description and it started working. Once again thanks for the help:)
