### ISSUE TITLE
Share session logs not working

### ISSUE THREAD

**Issue by SamiYousef** [kasketis/netfox#153]
[MC] Filtering mail sheet accounts for bundle ID: com.xx.xx, source account management: 1

**Comment by vGubriienko** [comment]
Can't reproduce.

**Comment by jeet-chanchawat** [comment]
https://user-images.githubusercontent.com/2392078/217751370-1448fafd-293a-4ccf-a2ea-4cfc2d88577a.mov

Hi, The button under settings is not working. PFA video.

**Comment by Pe-te** [comment]
The canSendMail() returns false if the device has no mail app, no mail account setup or the user has a different email client like Outlook or Gmail.

Something like this could work to open other email clients:
https://stackoverflow.com/a/55765362
But not sure about the attachment, maybe you can only set it as the body and not sure if there is a limit.
Still better than nothing maybe.

Or use ShareKit to share the attachment with other apps like MS Teams.

Or maybe just add a hook in the canSendMail false branch, where people can do custom actions like showing a dialog or implementing other share mechanisms.
