### ISSUE TITLE
Xcode 10.2 carthage update, no Build

### ISSUE THREAD

**Issue by 1055843615** [kasketis/netfox#155]

**Comment by donpironet** [comment]
+1

**Comment by silnose** [comment]
same with cocoapod

**Comment by vGubriienko** [comment]
Thanks for your report! Currently we can't reproduce the issue and close it. You could reopen it anytime if you still can reproduce it.

**Comment by 1055843615** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
