### ISSUE TITLE
How to know it is started already?

### ISSUE THREAD

**Issue by tanpengsccd** [kasketis/netfox#162]
How to know it is started already?

**Comment by felipeflorencio** [comment]
Hey, nice that you trying but can you be more specific? Like, did you follow the README and something went wrong?

**Comment by tanpengsccd** [comment]
i have started as readme.md. `NFX.sharedInstance().start()` ,but I don't konw it's status like started 
 or stoped?

**Comment by felipeflorencio** [comment]
Did you did this?

Usage
Just shake your device and check what's going right or wrong! Shake again and go back to your app! 

Stop
Call

NFX.sharedInstance().stop()
to stop netfox and clear all saved data. If you stop netfox its view will not be displayed until you call start method again.

If you want to just enable/disable logging functionality or clear the data please use the buttons provided in the settings view

**Comment by felipeflorencio** [comment]
Understanding that it's ok, I will close, any further question's please let us know

**Comment by tanpengsccd** [comment]
i mean that I want switchUI to  show the state of NFX.

**Comment by tabynbayev** [comment]
I made a pull request to handle this case - https://github.com/kasketis/netfox/pull/163
