### ISSUE TITLE
Doesn't catch Kingfisher's image requests

### ISSUE THREAD

**Issue by kohtenko** [kasketis/netfox#167]
While using https://github.com/onevcat/Kingfisher to download, cache and display images, the library doesn't show those downloads at all

**Comment by mullerfrederik** [comment]
`import Foundation
import netfox

final class KingfisherSetup {
    static let configuration: URLSessionConfiguration = {
        let configuration = URLSessionConfiguration.default
        configuration.protocolClasses?.insert(NFXProtocol.self, at: 0)  <--- THIS :)
        configuration.requestCachePolicy = .returnCacheDataElseLoad
        configuration.urlCache = .shared
        return configuration
    }()
}
`

**Comment by vGubriienko** [comment]
Closed due to inactivity.
