### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by blg-nb** [kasketis/netfox#168]
Hey,

can you implement the Swift Package Manager

Thanks

**Comment by armintelker** [comment]
i would love this too

**Comment by blg-nb** [comment]
me too

**Comment by armintelker** [comment]
is there some progress on this topic

**Comment by valexa** [comment]
Doesn't look like it

**Comment by ismailkilic** [comment]
We are still waiting

**Comment by aureliendelrue** [comment]
Me too please

**Comment by asimtemur** [comment]
i am waiting too.

**Comment by gbreen12** [comment]
I've started this process on this pull request: https://github.com/kasketis/netfox/pull/204

Unfortunately I only have time right now to make it work for iOS and Swift (No macOS, no Obj-C). If anyone wants to contribute to that to expand it feel free.

**Comment by kasketis** [comment]
https://github.com/kasketis/netfox/releases/tag/1.20.0
