### ISSUE TITLE
Can't load image from netfox version 1.15.1

### ISSUE THREAD

**Issue by anhhtchy** [kasketis/netfox#175]
when I create UIImage, If I use netfox version 1.15.0, the image is shown.
If I use netfox version > 1.15.0, image don't show.
`UIImage(named: "bubbleTailLeft", in: Bundle.bundleName, compatibleWith: nil)?.resizableImage(withCapInsets: UIEdgeInsets(top: 17, left: 21, bottom: 17, right: 21), resizingMode: .stretch).withRenderingMode(.alwaysTemplate)`

**Comment by juliensagot** [comment]
We have the same issue in our project.
The method swizzling in the `swizzleProtocolSetter` function in `NFXHelper.swift` file may be the root cause of this particular issue.

**Comment by vGubriienko** [comment]
@anhhtchy  I've tried with provided code (only replaced `Bundle.bundleName` with `Bundle.main` and stored image in assets catalog) and everything is work fine on the latest version.
