### ISSUE TITLE
Cannot close netfox on iPad

### ISSUE THREAD

**Issue by steelzeh** [kasketis/netfox#179]
There currently is an issue if you navigate into a request, and then go back you can no longer close netfox, but shaking will open a second netfox window.

**Comment by HenriquePer5** [comment]
Hi! i just open a PR with a possible solution for this. Take a look a see what you think 🙂

**Comment by bordoli** [comment]
Same problem here

**Comment by felipeflorencio** [comment]
Merged, let me know if any problem shows up, thx guys
