### ISSUE TITLE
Log screen pushed multiple times with shake after navigating to settings screen on iOS 13

### ISSUE THREAD

**Issue by olcayertas** [kasketis/netfox#183]
Steps to reproduce:
- Shake to open log view
- Press settings button to open settings screen
- If you shake screen in settings view log screen will be pushed again
- Go back to log view
- If you shake screen in log view log screen will be pushed again

If you don't go to settings, shaking will hide the log view.

Platform: iOS 13

**Comment by vGubriienko** [comment]
Can't reproduce on latest version 1.20.0.
