### ISSUE TITLE
Netfox suitable version for minimum iOS 8 on swift version > 3

### ISSUE THREAD

**Issue by michellemmy** [kasketis/netfox#188]
Hi, I'd like to ask for opinion.
I'm currently using Xcode 10.1 with minimum version of iOS 8 and currently on swift 4.2
I notice that since April 2019, this library has set the minimum iOS to iOS 9.
Is there any option for me to keep using this library and maintain the minimum version of iOS ?

Thanks for your help :)

**Comment by vGubriienko** [comment]
You could use old versions of the lib. Actual version now supports only from Swift 5.x
