### ISSUE TITLE
This repository uses UIWebview instead of using WKWebview which is not supported by Apple appstore guildlines

### ISSUE THREAD

**Issue by arjungupta0107** [kasketis/netfox#197]
When i am searching for `UIWebView` then i found there is `UIWebView` in `WebViewController.swift` file which is not supported by Apple app store guide lines. see this
<img width="662" alt="Screenshot 2020-03-20 at 6 32 57 PM" src="https://user-images.githubusercontent.com/37107527/77165915-423d9100-6ad9-11ea-8025-d416c99b0227.png">
Any workaround for this?

**Comment by jnevesjunior** [comment]
I have this problem too

**Comment by tommy19970714** [comment]
I made a sample code for WKWebView.
Please check my repository.
https://github.com/tommy19970714/WebKitURLProtocol/tree/master

**Comment by MarcoSantarossa** [comment]
Do we have any update on this ? Is this repository still maintained ?

**Comment by ankitgarg1mg** [comment]
I think you should not send this code in production. For this you can add basic check while installing pod

  pod 'netfox', '1.19', :configurations => ['Staging', 'Dev']

**Comment by vGubriienko** [comment]
UIWebView present only in the demo app. There is no mentions inside the framework.
