### ISSUE TITLE
Override/Change gesture/Way to show logs

### ISSUE THREAD

**Issue by vCrespoP** [kasketis/netfox#2]
It would be nice to have the ability to define our own method/gesture and call everything with one access method. Imagine this mixes up with shaking in some application, or we want to have a button always there to just display when the tester taps, etc.

Thanks!

**Comment by vCrespoP** [comment]
We can use this:

NFX.sharedInstance().show()
NFX.sharedInstance().hide()

Fair enough.

**Comment by kasketis** [comment]
I'm working on this right now! You will get my update soon :)

**Comment by kasketis** [comment]
Ready! Give it a try and let me know :)

**Comment by vCrespoP** [comment]
Sorry, getting strange behaviors. 

Please call start(.custom) first, when that method cannot accept parameters, I think the condition to show NFX is wrong depending on if it's custom or shake. Could please check it this is happening for you? Maybe writing a unit test to validate it?

Another thing (I don't know if this could be a side effect) is that sometimes I don't get any request printed in the tableView but if I reinstall the app it shows them back again.

**Comment by kasketis** [comment]
The error message it's incorrect. I will fix it.
Please verify that your code is like this

didFinishLaunchingWithOptions:
<pre>
NFX.sharedInstance().start()
NFX.sharedInstance().setGesture(.custom)
</pre>

Then when you want to show your logs call
<pre>
NFX.sharedInstance().show()
</pre>

**Comment by vCrespoP** [comment]
Ok, it works. Just one thing to notice:
If you set the gesture to .shake and try to open like:

``` NFX.sharedInstance().show() ```

That doesn't work, I suppose that's an intended behavior. 

I don't know if you want to support multiple ways to open it (shake + custom + ...) to make something with flags like [.shake, .custom], but maybe it's a good idea.

Thanks for your availability and quickness :D

**Comment by kasketis** [comment]
It's a good idea, so maybe I will add it in a future release. Thanks :)
