### ISSUE TITLE
KFSwiftImageLoader

### ISSUE THREAD

**Issue by mpsmith** [kasketis/netfox#21]
Great tool!

Would you expect this to work with https://github.com/kiavashfaisali/KFSwiftImageLoader  ?

I'm able to see other request/responses in netfox, except for those...

**Comment by kasketis** [comment]
Thanks for the info! I will check it and get back to you! :)

**Comment by kasketis** [comment]
Hi! I managed to get it work by replacing the 
<pre>
    internal lazy var session: NSURLSession = {
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.requestCachePolicy = .ReturnCacheDataElseLoad
        configuration.URLCache = .sharedURLCache()
        return NSURLSession(configuration: configuration)
    }()
</pre>

with this

<pre>
    internal lazy var session: NSURLSession = {
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.protocolClasses?.insert(NFXProtocol.self, atIndex: 0) //added line
        configuration.requestCachePolicy = .ReturnCacheDataElseLoad
        configuration.URLCache = .sharedURLCache()
        return NSURLSession(configuration: configuration)
    }()
</pre>

in the KFImageCacheManager.swift file

Attention: You will get image log only the first time because KFSwiftImageLoader caches the images and doesn't request them again

Please verify the workaround :)

**Comment by kasketis** [comment]
Also make sure you delete the app from the device/simulator and make a Product > Clean before you rebuild

**Comment by mpsmith** [comment]
Hey Thanks!   Confirmed this works in principal, though it was a little tricky coming up with a way to do it using both KF and NF as cocoa pods.  Ended up exposing a way to modify the session configuration in KFSwiftImageLoader from the app (which has visibility to Netfox module).

Cheers.

**Comment by kasketis** [comment]
Nice :) Could you please post your workaround?

**Comment by mpsmith** [comment]
All I did was to provide a way for an app to override the session configuration before the NSURLSession in KFImageCacheManager is initialized.   

```
    public static var sessionConfigurationOverride: NSURLSessionConfiguration?

    lazy var session: NSURLSession = {
        if let config = sessionConfigurationOverride {
          return NSURLSession(configuration: config)
        } else {
          let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
          configuration.requestCachePolicy = .ReturnCacheDataElseLoad
          configuration.URLCache = .sharedURLCache()
          return NSURLSession(configuration: configuration)
        }
    }()
```

Then, upon starting the app, inject a config that puts the NFXProtocol in the middle to capture the image requests
```
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.protocolClasses?.insert(NFXProtocol.self, atIndex: 0)
        configuration.requestCachePolicy = .ReturnCacheDataElseLoad
        configuration.URLCache = .sharedURLCache()
        KFImageCacheManager.sessionConfigurationOverride = configuration
```

It like a bit of a run-around, but it's working.

**Comment by Janglinator** [comment]
PR #94 will solve issues like these

**Comment by kasketis** [comment]
Since #94 merged, I consider it as solved. Please come back with a new issue if not. 👍
