### ISSUE TITLE
Issue using URLSessionWebSocketTask when netfox is running.

### ISSUE THREAD

**Issue by IceTrae** [kasketis/netfox#210]
**Describe the bug**
If netfox is running and an attempt is made to open a web socket connection using URLSessionWebSocketTask a crash will occur.
EXC_BAD_ACCESS (code=1, address=0x0)

**To Reproduce**
Run example project: https://github.com/IceTrae/NetfoxCrashExample

- or -

Execute the following while netfox is running:

```
        guard let url = URL(string: "wss://echo.websocket.org") else {
            return
        }
        
        var webSocketTask = URLSession.shared.webSocketTask(with: url)
        webSocketTask.resume()
```

**Expected behavior**
Best case, log the socket network traffic. Just ignoring the web socket altogether would also be fine. Just don't cause a crash.

**Enviroment:**
 - Device: iPhone 12 Pro Simulator
 - OS: iOS 14.5
 - Netfox version: 1.19.0
-  Xcode version: 12.5.1
-  Swift version: 5

**Comment by vGubriienko** [comment]
Currently log streaming traffic is not an easy task so just fix the issue by ignoring such requests.
