### ISSUE TITLE
Crash after changing the type of response that can be displayed

### ISSUE THREAD

**Issue by SuperDiG** [kasketis/netfox#214]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Enviroment:**
 - Device: [e.g. iPhone 8 plus]
 - OS: [e.g. iOS 14.2]
 - Netfox version: [e.g 1.15.0]
-  Xcode version: [e.g 12.3]
-  Swift version: [e.g 5.3.2]

**Additional context**

question：
A crash occurs when the page returns after modifying the desired response condition on the Settings screen. After debugging, it is found that the data is out of bounds. It will not crash after I add out of bounds judgment. If you have a better solution please fix this problem.

The code I fixed is as follows

```
// fileName: NFXListController_iOS.swift
// line: 140

func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
    {
        let cell = self.tableView.dequeueReusableCell(withIdentifier: NSStringFromClass(NFXListCell.self), for: indexPath) as! NFXListCell
        
        if (self.searchController.isActive) {
            if (self.filteredTableData.count > 0) && (indexPath.row < NFXHTTPModelManager.sharedInstance.getModels().count) {
                let obj = self.filteredTableData[(indexPath as NSIndexPath).row]
                cell.configForObject(obj)
            }
        } else {
            if (NFXHTTPModelManager.sharedInstance.getModels().count > 0) && (indexPath.row < NFXHTTPModelManager.sharedInstance.getModels().count) {
                let obj = NFXHTTPModelManager.sharedInstance.getModels()[(indexPath as NSIndexPath).row]
                cell.configForObject(obj)
            }
        }
        
        return cell
    }
```

**Comment by bstillitano** [comment]
Library is abandoned, use [Scyther](https://GitHub.com/bstillitano/Scyther)
