### ISSUE TITLE
Question: How does WKWebView Hook work?

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [kasketis/netfox#218]
Hi man, GOOD DAY
I have 2 questions about this amazing repo.

1. NSURLProtocol does not work with WKWebView, But how does your repo work with? Where are the key codes?
2. I send http request via NSURLConnection, but the delegate I setup to NSURLConnection was not called, why?

**Comment by vGubriienko** [comment]
1. Netfox currently doesn't support WKWebView. You could see only mock in demo app.
2. Could you provide code example?
