### ISSUE TITLE
Crash writing if no space left on device

### ISSUE THREAD

**Issue by lisemyon** [kasketis/netfox#221]
**Describe the bug**
An application is crashing if no space left on device for writing data in a file.

**To Reproduce**
1. Simulate no memory left for writing any more log files. (ex: https://www.avanderlee.com/debugging/no-space-left-on-device/)
2. Make requests till the crash (ex: load images/jokes in example app)

**Expected behavior**
Writing is stopped if no space available

**Enviroment:**
 - Device: iPhone 12
 - OS: iOS 15.1
 - Netfox version: 1.20.0
-  Xcode version: 13.1
-  Swift version: 5.1

**Additional context**
The reason of crashing is probably fileHandle.write method as it does not throw any exception

**Comment by vGubriienko** [comment]
Thanks for your report! We are currently working on resolving this issue.
