### ISSUE TITLE
Exported curl don't work on postman for requests with more than one query  param

### ISSUE THREAD

**Issue by PM74367** [kasketis/netfox#223]
**Describe the bug**
When we  go to  request  details, and export request as curl,  and try  to import  that  as raw text  in postman, import fails

**To Reproduce**
1. Go to 'detail screen of a request with more than one query param'
2. Click on 'export button  at top of screen'
3. Select 'export curl as request'
4. Select 'copy'
5. Paste in postman by going to import -> raw text
6. Click continue -> import

<img width="818" alt="Screenshot" src="https://user-images.githubusercontent.com/47234953/150647423-41952826-6f9b-4f38-b860-5b4c01551884.png">
<img width="352" alt="Screenshot" src="https://user-images.githubusercontent.com/47234953/150647445-8eb55ece-394b-421c-832e-0e5273b5850e.png">

**Comment by vGubriienko** [comment]
Thx for your report! Will check this.
