### ISSUE TITLE
Upload Progress Method from Alamofire don't called when use netfox

### ISSUE THREAD

**Issue by anirudhamahale** [kasketis/netfox#228]
**Describe the bug**
I use Alamofire for network request & netfox for logging the request.
The `uploadProgress` closure never gets called if I enable the netfox like so `NFX.sharedInstance().start()` in AppDelegate.

```swift 
AF.upload(multipartFormData: { (multipartFormData) in
        multipartFormData.append(fileUrl, withName: "file")
        multipartFormData.append("\(id)".data(using: String.Encoding.utf8, allowLossyConversion: false)!, withName: "customer_id")
    }, to: Constants.kAddMedia, headers: Constants.kHeaders)
    .uploadProgress { (prgs) in
        progress(Float(prgs.fractionCompleted))
    }
    .responseJSON { response in
      // do my stuff 
    }
}
```

**Enviroment:**
 - Device: [e.g. iPhone 7]
 - OS: [e.g. iOS 15.1]
 - Netfox version: [e.g 1.20.0]
 - Alamofire version: [e.g 5.4]
-  Xcode version: [e.g 13.2.1]
-  Swift version: [e.g 5]

**Additional context**
here is the [link](https://github.com/Alamofire/Alamofire/issues/2972) to the issue from Alamofire

**Comment by ersinkhr** [comment]
Same here. When I deintegrate Netfox pod, everything works.

**Comment by vGubriienko** [comment]
Thanks for the report. Will check as soon as possible.

**Comment by renanstig** [comment]
It's been more than a year, has this issue been fixed?

**Comment by anirudhamahale** [comment]
Yes it's been fixed @renanstig

**Comment by Osein** [comment]
I am using 1.21.0 version of netfox and in the below progress handler doesnt get called

`AF.upload(multipartFormData: { formData in
            for (key, value) in formFields {
                if let data = value.data(using: .utf8) {
                    formData.append(data, withName: key)
                }
            }
            formData.append(url, withName: formFields["name"] ?? "attachment")
        }, with: request).uploadProgress { progress in
            progressHandler?(progress.fractionCompleted)
        }.responseData`

**Comment by renanstig** [comment]
> I am using 1.21.0 version of netfox and 5.6.4 of Alamofire, in the below progress handler doesnt get called
> 
> ` AF.upload(multipartFormData: { formData in
> 
> ```
>         for (key, value) in formFields {
>             if let data = value.data(using: .utf8) {
>                 formData.append(data, withName: key)
>             }
>         }
>         formData.append(url, withName: formFields["name"] ?? "attachment")
>     }, with: request).uploadProgress { progress in
>         progressHandler?(progress.fractionCompleted)
>     }.responseData
> ```
> 
>

> I am using 1.21.0 version of netfox and 5.6.4 of Alamofire, in the below progress handler doesnt get called
> 
> ` AF.upload(multipartFormData: { formData in
> 
> ```
>         for (key, value) in formFields {
>             if let data = value.data(using: .utf8) {
>                 formData.append(data, withName: key)
>             }
>         }
>         formData.append(url, withName: formFields["name"] ?? "attachment")
>     }, with: request).uploadProgress { progress in
>         progressHandler?(progress.fractionCompleted)
>     }.responseData
> ```
> 
> `

Unfortunately I have faced the same issue as you, even though they say the problem is fixed, it isn’t

my workaround to it was to deactivate Netfox before the upload starts and then restart it after it’s done
