### ISSUE TITLE
Doesn't work with AFNetworking 2.6.1

### ISSUE THREAD

**Issue by Pitsko** [kasketis/netfox#27]
Netfox doesn't show any requests that was send with AFNetworking 2.6.1

**Comment by kasketis** [comment]
Hello @Pitsko ,
Thanks for the issue! Could you please post a sample code of a request of yours in order to reproduce the problem?

**Comment by Chintan-Dave** [comment]
I am getting same kind of issue while using AFNetworking 2.6.3. I make subclass of AFHTTPSessionManager and make it singleton. White creating singleton I use following line to make it work.
        NSURLSessionConfiguration *config = [NSURLSessionConfiguration defaultSessionConfiguration];
    
        config.protocolClasses = @[[NFXProtocol class]];

I think we have to add NFXProtocol class so AFNetworking call require method to listen request. I hope this will help in some way.

**Comment by kasketis** [comment]
Hello all,
I have created a sample ObjC project with AFNetworking 2.6.1 to reproduce the issue.
My code based on  "HTTP Request Operation Manager" section of http://cocoadocs.org/docsets/AFNetworking/2.6.1/

<pre>
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [[NFX sharedInstance] start];
    
    AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
    
//    GET
    [manager GET:@"https://www.github.com" parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
        NSLog(@"Response: %@", responseObject);
    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        NSLog(@"Error: %@", error);
    }];
    
//    POST
    NSDictionary *parameters = @{@"foo": @"bar"};
    [manager POST:@"https://www.github.com" parameters:parameters success:^(AFHTTPRequestOperation *operation, id responseObject) {
        NSLog(@"Response: %@", responseObject);
    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        NSLog(@"Error: %@", error);
    }];
    
    
    return YES;
}
</pre>

I didn't subclass or do anything more than just start the netfox

With the above got I managed to log both requests without any problem
![screen shot 2015-11-30 at 10 28 55 am](https://cloud.githubusercontent.com/assets/2895107/11467002/e4d614fa-974d-11e5-8c72-519ba90365c5.png)

I got the same successful results with AFNetworking 2.6.3

Could you please share your requests code?

**Comment by xuyunan** [comment]
Same issue When i use Alamofire(https://github.com/Alamofire/Alamofire)

**Comment by kasketis** [comment]
@xuyunan for Alamofire please check this https://github.com/kasketis/netfox/blob/master/Workarounds.md#alamofire-workaround

**Comment by Pitsko** [comment]
I think main issue, because we are using AFNetworking together with ReactiveCocoa
and we use this library https://github.com/glyuck/AFNetworking-RACExtensions.git' as bridge between AFNetworking and Reactive

inside this library you can see some workaround

- (RACSignal *)rac_requestPath:(NSString *)path parameters:(id)parameters method:(NSString *)method {
	return [RACSignal createSignal:^(id<RACSubscriber> subscriber) {
		NSURLRequest *request = [self.requestSerializer requestWithMethod:method URLString:[[NSURL URLWithString:path relativeToURL:self.baseURL] absoluteString] parameters:parameters error:nil];
		
		NSURLSessionDataTask *task = [self dataTaskWithRequest:request completionHandler:^(NSURLResponse *response, id responseObject, NSError *error) {
			if (error) {
				NSMutableDictionary *userInfo = [error.userInfo mutableCopy];
				if (responseObject) {
					userInfo[RACAFNResponseObjectErrorKey] = responseObject;
				}
				NSError *errorWithRes = [NSError errorWithDomain:error.domain code:error.code userInfo:[userInfo copy]];
				[subscriber sendError:errorWithRes];
			} else {
				[subscriber sendNext:RACTuplePack(responseObject, response)];
				[subscriber sendCompleted];
			}
		}];
		[task resume];
		
		return [RACDisposable disposableWithBlock:^{
			[task cancel];
		}];
	}];
}

**Comment by kasketis** [comment]
Please check this https://github.com/kasketis/netfox/blob/master/Workarounds.md#99

**Comment by Pitsko** [comment]
I tried it , and it doesn't work

**Comment by kasketis** [comment]
Could you please post your requests code?

**Comment by engineeringman** [comment]
I'd like to restart this issue:  It's still occurring with AFNetworking 3.0.2.  Here's a quick example of my AFNetworking call (We're using AFHTTPSessionManager, so I duplicated that functionality in my sample code):

```
    NSString *urlString = @"http://images2.fanpop.com/image/photos/9400000/Aaaaaawwwwwwwwww-Sweet-puppies-9415255-1600-1200.jpg";
    
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    
    [manager setResponseSerializer:[AFHTTPResponseSerializer serializer]];
    [manager.responseSerializer setAcceptableContentTypes:[NSSet setWithObjects:@"text/html", @"image/jpeg", nil]];
    
    [manager GET:urlString parameters:nil progress:^(NSProgress * _Nonnull downloadProgress) {
        
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        
        UIImage *image = [UIImage imageWithData:responseObject];
        // Just to ensure the image loaded correctly.
        //[self.imageView setImage:image];
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        
    }];
```

I'm calling `[[NFX sharedInstance] start];` Inside my app delegate's `didFinishLaunchingWithOptions:`, however none of the requests show up.

I've tried placing the following block:
```
NSURLSessionConfiguration* config = NSURLSessionConfiguration.defaultSessionConfiguration;
config.protocolClasses = @[[NFXProtocol class]];
```
in multiple places, including before and after `[[NFX sharedInstance] start];`, and after creating the 'AFHTTPSessionManager'.  Nothing appears to work.

**Comment by engineeringman** [comment]
That was a complete lack of research on my part;  I thought `defaultSessionConfiguration` returned a static instance.  We need to pass that configuration to AFNetworking in order to have it use the proper protocol.  Example code:

```
    NSString *url = @"http://images2.fanpop.com/image/photos/9400000/Aaaaaawwwwwwwwww-Sweet-puppies-9415255-1600-1200.jpg";
    
    NSURLSessionConfiguration *config = [NSURLSessionConfiguration defaultSessionConfiguration];
    
    config.protocolClasses = @[[NFXProtocol class]];
    
    AFHTTPSessionManager *manager = [[AFHTTPSessionManager alloc] initWithBaseURL:nil sessionConfiguration:config];
    
    [manager setResponseSerializer:[AFHTTPResponseSerializer serializer]];
    [manager.responseSerializer setAcceptableContentTypes:[NSSet setWithObjects:@"text/html", @"image/jpeg", nil]];
    
    [manager GET:url parameters:nil progress:^(NSProgress * _Nonnull downloadProgress) {
        
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {

        UIImage *image = [UIImage imageWithData:responseObject];
        // Just to ensure the image loaded correctly.
        //[self.imageView setImage:image];
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        
    }];
```

**Comment by zdurlan** [comment]
It does not work for me with AFNetworking 3.0.x, if I do what Janglinator suggested, my requests just stop working and I never get any response from the server and netfox does not record any requests.

**Comment by Janglinator** [comment]
I'm assuming pr #94 would also solve this issue.  We'd have to test against it to confirm, but I think just about everybody has switched to Alamofire by now

**Comment by Janglinator** [comment]
Going to close this issue, I believe it has been resolved
