### ISSUE TITLE
Crash "configForObject"

### ISSUE THREAD

**Issue by vCrespoP** [kasketis/netfox#3]
This method is crashing, you should never unwrap variables without using 'guard' or 'if let' or define a default value

    func configForObject(obj : NFXHTTPModel)
    {

...
        
        setStatus(obj.responseStatus!)
        setTimeInterval(obj.timeInterval!)
        setRequestTime(obj.requestTime!)
        setType(obj.responseType!)
        setMethod(obj.requestMethod!)
    }

I propose not using them if they're not present and handle those cases, or simplest way:

        setStatus(obj.responseStatus ?? 999)
        setTimeInterval(obj.timeInterval ?? "-")
        setRequestTime(obj.requestTime ?? "-")
        setType(obj.responseType ?? "-")
        setMethod(obj.requestMethod ?? "-")

You're the father, your call :D

**Comment by kasketis** [comment]
You are right! Fixed. Thanks :)
