### ISSUE TITLE
Requests don't show for applications that use a custom NSURLSessionTask

### ISSUE THREAD

**Issue by michaelfransen** [kasketis/netfox#32]
I was seeing some of my frameworks requests but I wasn't seeing them from my own app. I did some debugging and found that if your app uses a NSURLSessionConfiguration class and uses NSUrlSessionTasks, you must set the protocol class yourself. 

Also, in NFXProtocol, you must implement the following method.

```
override public class func canInitWithTask(task: NSURLSessionTask) -> Bool {
        if !NFX.sharedInstance().isEnabled() {
            return false
        }
        
        if let url = task.currentRequest?.URL {
            if (!(url.absoluteString.hasPrefix("http")) && !(url.absoluteString.hasPrefix("https"))) {
                return false
            }
            
            for ignoredURL in NFX.sharedInstance().getIgnoredURLs() {
                if url.absoluteString.hasPrefix(ignoredURL) {
                    return false
                }
            }
        } else {
            return false
        }
        
        if NSURLProtocol.propertyForKey("NFXInternal", inRequest: task.currentRequest!) != nil {
            return false
        }
        
        return true
    }
```

I will try to get around to making a pull request, but I wanted to post this in case other people weren't seeing all of their traffic.

**Comment by kasketis** [comment]
Nice finding @michaelfransen :+1: 

If you want to use the same code as in canInitWithRequest please make a new method canServeRequest(request: NSURLRequest) -> Bool
and move all checks there. Then call this method from canInitWithRequest: and canInitWithTask:.

I'm waiting for your pull request :) Thanks !

**Comment by kasketis** [comment]
Also if you use your custom NSURLSessionConfiguration you must do something like this
         
<pre>
let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
configuration.protocolClasses?.insert(NFXProtocol.self, atIndex: 0)
....
</pre>

**Comment by michaelfransen** [comment]
Cool, I skipped over that because I wasn't using alamofire. I ended up doing

```
NSURLSessionConfiguration* config = NSURLSessionConfiguration.defaultSessionConfiguration;
config.protocolClasses = @[[NFXProtocol class]];
```

**Comment by michaelfransen** [comment]
I wish there was a way around this, because I really like when a user just has to add ```[[NFX sharedInstance] start];``` and not have to do anything more codewise in their project.

**Comment by kasketis** [comment]
I will check it again but it seems that's the only way for now :) Thanks :+1:
