### ISSUE TITLE
why not support iOS7

### ISSUE THREAD

**Issue by Jia-Shen** [kasketis/netfox#35]
why not support iOS7?

**Comment by kasketis** [comment]
Hello @Jia-Shen , 
netfox uses some methods and protperties which are only available on iOS8 or newer.

**Comment by halmueller** [comment]
Accordng to mixpanel.com, all iOS versions older than iOS 8 have a combined share of about 5%. That number can only get smaller.

**Comment by kasketis** [comment]
@halmueller  +1 :+1:
