### ISSUE TITLE
Using Netfox without modal presentation

### ISSUE THREAD

**Issue by Janglinator** [kasketis/netfox#36]
I've created a project where I having a large selection of debugging tools built into one debugging window.  Netfox is spectacular, and I'd like to add it as another section of the pod.  However I don't wish to present it modally, but rather push it onto my existing navigation controller.  Is there any way we could publicly expose the NFXListController class for custom usage?

P.S. my library is in ObjC, so an @objc at the top would also be awesome!

**Comment by kasketis** [comment]
Hi @engineeringman , 
Thanks so much for your kind words and sorry for the response delay :)
Presenting NFXListController by your own is not recommended because it can cause bugs.
I will check how it can be safely implemented in the next release :+1:

**Comment by vCrespoP** [comment]
+1 Please, this would be very nice to have.

**Comment by vCrespoP** [comment]
No news on this? :sob:

**Comment by engineeringman** [comment]
Looking at the source, I'm not seeing how it could present bugs...  I actually made the changes to expose it locally, and locked my pod installation version to avoid it breaking with `pod update`.  It's been working great!  I'll make a pr later, if I remember

**Comment by vCrespoP** [comment]
Pull request or fork please ;)

**Comment by kasketis** [comment]
Presenting netfox without use of showNFX/hideNFX methods could present bugs - internal properties and notifications (basically used to determine new added requests) won't be called.

**Comment by colinhumber** [comment]
I've been using NFXListController on it's own for months and haven't run into any issues with pushing it onto an existing navigation controller. Which properties are being set? Looking at `showNFX` and `hideNFX`, the only property referenced is `presented`. Can you let us know exactly which properties and notifications aren't being called?

**Comment by vGubriienko** [comment]
Moved to project.
