### ISSUE TITLE
Proper casing in project naming

### ISSUE THREAD

**Issue by michaelfransen** [kasketis/netfox#39]
I've noticed that this is the only framework that I use that has the framework name lowercased. @kasketis - Was this intentional? Do you mind if we update it to Netfox instead of netfox?

**Comment by kasketis** [comment]
Hi @michaelfransen ,
Sorry for the response delay.
I think that the name of the framework is the same with the name of the project - so we must change the project name to Netfox.xcodeproj - right?

**Comment by michaelfransen** [comment]
Yeah, that is my understanding. Even if we can set it differently, it would be good to be consistent.

**Comment by Janglinator** [comment]
I definitely agree with this, it's driven me crazy since the day I discovered Netfox  :)

Any thoughts @kasketis?

Check out:  [Pod Deprecation](https://stackoverflow.com/a/36928723/2101268)

**Comment by kasketis** [comment]
OK guys! After a long time, I'm sold 😄 Please @Janglinator proceed with this ;)

**Comment by kasketis** [comment]
@Janglinator But please before you proceed, one question: what will happen to the existing users? Must all of them update their podfile?

**Comment by Janglinator** [comment]
Check out the link I posted in my last comment

**Comment by kasketis** [comment]
I have checked it but still it's not clear to me what is gonna happen. Do you have a clear view on this?

**Comment by Janglinator** [comment]
I don’t :/ I’ll read into it tonight.  It *sounds* like the pod update will fail with a message, and the user will have to change their podfile

**Comment by Janglinator** [comment]
From the looks of it, it seems the user's pod install/update will fail, with a message stating it's been deprecated in favor of 'Netfox'.  I can't find much more info, and I also can't find an example of a pod that's been properly deprecated to test against.

**Comment by Janglinator** [comment]
https://guides.cocoapods.org/syntax/podspec.html#deprecated_in_favor_of

Seems like we'd need to add this spec option to our podfile, push a trunk release, then update the spec file.

**Comment by vGubriienko** [comment]
Moved to project.
