### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by tbaranes** [kasketis/netfox#42]
Starting a first suggestion in #28 for OSX support, you seemed to be interested in it. Is there any work started yet? If no, would you be interested in a PR to handle it? (if I have the time to work on it...) Or just some helps? 

We are really interested on this since we already using Netfox in our iOS application :)

**Comment by kasketis** [comment]
Hi tbaranes,

Unfortunately no work have started yet due to lack of free time. 
Of course I'm interested in any PR that handles it

Thanks!

**Comment by tbaranes** [comment]
Alright, I'll look at it once I have time... one day :laughing:

**Comment by tbaranes** [comment]
I just looked at the code, and I already have some questions!

How do you prefer that the library's architecture evolve to be OSX compliant? I think the easier way to implement it, and staying generic, is to abstract `NFXGenericController` to be mac compliant by using  the same public methods. I just made a try [NFXHelper class](https://github.com/kasketis/netfox/compare/master...tbaranes:master). Also, we will probably have to divide some classes (`NFX`, ...) to avoid too much `if os(iOS)...`, the best solution is probably extension for each platform.

Also, is it ok to put the iOS interface in a `NSWindow` or do you want be more "mac"?

That's just a first look into it, I don't have all the keys yet, but it would be great to what do you prefer about `Netfox` evolution!

**Comment by kasketis** [comment]
I like the way you think :) Please keep the same public methods as you did on NFXHelper class.

I don't have any serious experience on OSX platform so I need your opinion on NSWindow.
What do you think is the best way to present the logs on OSX app developers/users?
What changes must we make on the current interface to put it in a NSWindow? Can we use it as is?
A more "mac" way requires a new UI, right?
If yes I think the following structure can handles it easy.

Generic (parent with the common core functionality)
- iOS Child (ios things)
- OSX Child (osx things)

For example
NFXDetailsGenericController
- NFXDetailsController_iOS
- NFXDetailsController_OSX

As about your last question, I prefer to create the UI via code because it's easier for collaboration and changes tracking (merges, conflicts, etc)

**Comment by tbaranes** [comment]
Yeah, abstracting as much as possible the code will be the easiest way! I did it yesterday on `NFX` to split the `showNFX` and `hideNFX` to be OSX compliant. It's a nice way to handle this issue.

For the mac interfaces, we have to rewrite all the code related to it. We can't use any  `UIKit` objects when targeting OSX platform. So, we have to replace `UITableView` by a `NSTableView`, adapt the delegate / datasource... so whatever the solution choose, a new UI will be implemented. We can keep the colors, fonts... basic stuff by having a `NFX...` (like  `NFXColor`, `NFXFont`...)

For the final display, I was thinking about a `NSSplitViewController`:
- On the left the list of all the requests
- On the right, the details when we clicked on a request. 
This way, we are keeping the same UI architecture  as iOS, just changing the navigation (that will be mandatory anyway).

Also, in order to replace the shake gesture (we can't shake our mac :(), I was thinking to add an item in the top menu of the application, with a keyboard shortcut to open netfox. I have to dig a bit more to check if this solution is possible.

Happy to see you agree with my thinking :+1:

**Comment by kasketis** [comment]
:+1: I appreciate your help. Please keep me informed of any update :beer:

**Comment by tbaranes** [comment]
I can't find a nice way to make in common `ENFXGesture` without some renaming. I think the nicest way in code would be to change `shake` by `default`, but that also means it will be less explicit during the usage.

Another solution, could be to have specific case by platform, `shake` on iOS, `menu` on mac, but we will have to duplicate the switch, `selectedGesture`...

Whatever is the final choice, I definitely think we should change `ENFXGesture` name, it will never have a chance on mac. I'm trying to keep as little as possible the number of breaking change, but can't see a way to avoid this one!

What do you think?

**Comment by kasketis** [comment]
I don't think I understand correctly the issue but is this a possible solution:

    #if os(iOS)
    private var selectedGesture: ENFXGesture = .shake
    #else //os(OSX)
    private var selectedGesture: ENFXGesture = .menu
    #endif

If not could you please explain it to me a little bit more?

Thanks

**Comment by tbaranes** [comment]
Yes, it's that, but `ENFXGesture` for a `menu` doesn't really make sense.

**Comment by tbaranes** [comment]
@kasketis We started without any xib / storyboards, but it's really painful to develop on mac without these features. Do you mind if for mac we use it? Anyway, creating everything programatically takes really too much time... :(

We are starting to make it with xib, hope you will be ok with that!

**Comment by kasketis** [comment]
I really don't like xibs/storyboards but I think it's ok for now for mac. If you don't mind, please use xib for each controller instead of storyboard. Thanks mate :+1:  :beer:

**Comment by tbaranes** [comment]
Alright, xib only, it's always better that nothing for us. Thanks for your comprehension :beers:

**Comment by kasketis** [comment]
OSX support added in 1.8 version!
