### ISSUE TITLE
Crash on the sharing button

### ISSUE THREAD

**Issue by tbaranes** [kasketis/netfox#44]
The crash is really easy to reproduce: always happening!

**Comment by kasketis** [comment]
I managed to successfully share the logs on my device (8.1.1). Could you please send me more info?
Is it related with this https://forums.developer.apple.com/thread/4415 ?

**Comment by tbaranes** [comment]
I have no crashlogs, but I just try with an iPhone 9.2, it's working well. The crash is happening on an iPad 9.2, and the only difference I see is that the iPad hasn't set an email account. 

From my crash reporter, here the log which not helping that much:

`Your application has presented a UIAlertController (<UIAlertController: 0x1419b4250>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem. If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.`

**Comment by kasketis** [comment]
In which state does it crash? When you press the share button or when you press simple/full log buttons?

**Comment by tbaranes** [comment]
Directly when I press the share button, the action sheet doesn't pop on the iPad

**Comment by kasketis** [comment]
Could you please replace the method actionButtonPressed with the following

<pre>
    func actionButtonPressed(sender: UIBarButtonItem)
    {
        let actionSheetController: UIAlertController = UIAlertController(title: "Share", message: "", preferredStyle: .ActionSheet)
        
        let cancelAction: UIAlertAction = UIAlertAction(title: "Cancel", style: .Cancel) { action -> Void in
        }
        actionSheetController.addAction(cancelAction)
        
        let simpleLog: UIAlertAction = UIAlertAction(title: "Simple log", style: .Default) { action -> Void in
            self.sendMailWithBodies(false)
        }
        actionSheetController.addAction(simpleLog)
        
        let fullLogAction: UIAlertAction = UIAlertAction(title: "Full log", style: .Default) { action -> Void in
            self.sendMailWithBodies(true)
        }
        actionSheetController.addAction(fullLogAction)
        
        if let popoverController = actionSheetController.popoverPresentationController {
            popoverController.barButtonItem = sender
        }
        
        self.presentViewController(actionSheetController, animated: true, completion: nil)
    }
</pre>

and check if the bug is still alive? :)

**Comment by tbaranes** [comment]
Yeah, this code fix the bug!

Just, don't forget to add `: ` in  `self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .Action, target: self, action: Selector("actionButtonPressed"))`
