### ISSUE TITLE
Large increase in memory usage with netfox enabled

### ISSUE THREAD

**Issue by radianttap** [kasketis/netfox#46]
I have an app which is doing somewhat large JSON imports very often in the background, like every 8-20s. The JSONs are parsed and saved into Core Data, all on the same backgorund thread/MOC.

With netfox compiled in, the memory usage became very large. 
I was not aware of at first that netfox is the cause of this, so I was removing my background operations one my one until I was left with just one call. Without netfox, app would take 40-44MB. With netfox, it was 84MB. When I added another JSON call following the first one, without netfox memory usage was around 54MB, with netfox it was 150MB. This was all without netfox UI ever being triggered - it was just doing its thing in the background.

If it helps - both of these JSON calls cause reading/updating and creating a lot of NSManagedObjects from my Core Data store. This all happens in background MOC/thread, thus it's gone from memory as soon as it's processed. But if netfox is somehow keeping something from that thread retained, then it could be a reason that all of the objects from the thread are staying in memory.

My app is Objective-C based and I really don't know Swift thus can't help debugging this.
Still, though it's worth reporting this.

**Comment by kasketis** [comment]
Hello and thanks for the issue!

Netfox saves request/respond body on disk to provide low memory overhead, so this is a little bit strange.
Unfortunately, I can't reproduce this, so is it possible to test it via Instruments app and let me know?

Thanks!

**Comment by radianttap** [comment]
At the moment no. What exactly would you want me to test in Instruments..?

**Comment by kasketis** [comment]
Just track memory usage via Leaks tool and check what happens in more depth

**Comment by Janglinator** [comment]
@kasketis Until this issue resurfaces, should we close out this issue?
