### ISSUE TITLE
How do I use with Objective-C project

### ISSUE THREAD

**Issue by grembe** [kasketis/netfox#47]
I am not sure how to use this framework with an Objective C project? Should there be a bridging header included in the framework, or do I need to somehow create one in xCode?

Thanks.

**Comment by davidkovaccs** [comment]
Hi @grembe,

You just need to import: "netfox-Swift.h"

Hope that helps!

**Comment by raheelahmad786** [comment]
I have imported the same #import "netfox-Swift.h" in my objective-c project. its not working. Please help i am in middle of it.

**Comment by KarimMagddi** [comment]
any updates please about this issue.

**Comment by linhVmodev** [comment]
Use `@import netfox;` instead
