### ISSUE TITLE
Filter by type

### ISSUE THREAD

**Issue by vCrespoP** [kasketis/netfox#5]
Can we make a method to configure Netfox to ignore certain types of requests or url extensions?

I'm thinking about an app that loads many images, and we just want the main interaction between app <=> server and not those resources.

**Comment by kasketis** [comment]
I added this https://github.com/kasketis/netfox#prevent-logging-for-specific-urls
Is that what are you looking for? :)

**Comment by vCrespoP** [comment]
Not exactly, it would be nice to define some kind of filter like:

"image/jpeg" type

or extension .jpg

**Comment by kasketis** [comment]
I have added filters. You can find them in settings page! Check them and please post your thoughts back :)
