### ISSUE TITLE
Caching broken with Netfox protocol

### ISSUE THREAD

**Issue by AvdLee** [kasketis/netfox#53]
When creating a custom manager to work with Alamofire:

``` swift
    static let sharedManager: TIFAlamofireManager = {
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.protocolClasses?.insert(NFXProtocol.self, atIndex: 0)
        configuration.HTTPAdditionalHeaders = Manager.defaultHTTPHeaders
        let manager = TIFAlamofireManager(configuration: configuration)
        manager.startRequestsImmediately = false
        return manager
    }()
```

The caching of URLRequests seems to be broken.

After disabling this line:

``` swift
configuration.protocolClasses?.insert(NFXProtocol.self, atIndex: 0)
```

Caching works as expected.

Anyone else encountering this issue?

**Comment by AvdLee** [comment]
Alright, it seems obvious why caching is not working.

This line inside the `NFXProtocol` disables caching:
```
self.client!.URLProtocol(self, didReceiveResponse: response!, cacheStoragePolicy: .NotAllowed)
```

What's the reason to disable caching on this level?

**Comment by Janglinator** [comment]
Thanks for the PR!  It's not mergeable at the moment, but I'll dig through and get it in

**Comment by Janglinator** [comment]
Resolved by e811faf7369b7a7f7c1d2c607afcaab835440e86

**Comment by invertercant** [comment]
it doesnt solve problem

**Comment by ergunkocak** [comment]
It does not work for me as well.

`NFX.sharedInstance().setCachePolicy(.allowed)`

has no effect. Still caches are dismissed.

fyi
