### ISSUE TITLE
Something wrong if there is oauth implemented in project

### ISSUE THREAD

**Issue by pratik6554** [kasketis/netfox#61]
Thank you for this library. Its helped a lot me. Quick way to check request and response.

I am trying to integrate human api (https://developer.humanapi.co), something wrong with Jawbone integration. I am not able to get few callbacks.

**Comment by Janglinator** [comment]
I know this was created a long time ago, but are you still having issues?

**Comment by pratik6554** [comment]
I have fixed that by calling NFX.sharedInstance().stop() before loading webview. And turned on after getting callback from webview.
