### ISSUE TITLE
UIWebView does not behave as expected when netfox is enabled.

### ISSUE THREAD

**Issue by 2ank3th** [kasketis/netfox#62]
We are using a third party payment gateway. Some of the tasks (like entering credit card ) are done in a webview. When netfox was enabled website was not behaving properly (Mostly probably because javascript were not loaded properly).

**Comment by T-Pham** [comment]
I also encountered some issues with redirecting in UIWebView when netfox is enabled and have managed to fix the issues like this: https://github.com/T-Pham/netfox/commit/bbce802d3c9b17369094343253e5c8f8372db064

Hope it could help our future readers.

**Comment by fdematos** [comment]
Same problem here. Please fix it

**Comment by Janglinator** [comment]
@fdematos @T-Pham @2ank3th Would anyone be able to test out a quick branch for me?

Use:
pod 'netfox', :git => 'https://github.com/kasketis/netfox.git', :branch => 'Issue_62'

If you can give me a quick thumbs up, I'll pull it in.

I tried testing this by using [https://jigsaw.w3.org/HTTP/300/Overview.html](https://jigsaw.w3.org/HTTP/300/Overview.html), however, it wasn't able to repeat the issue you're receiving.  Just let me know if the branch fixes the issue you're seeing.  If not, let me know a little more details of how you're using the webview, what urls you're loading, etc.

Thank you!

**Comment by T-Pham** [comment]
@Janglinator I just tested on my page with the published pod v1.9 and the branch Issue_62.
The issue occurred when using the published pod while it didn't with the branch Issue_62 so apparently the branch fixed the issue.
My test page does not do a 3xx http redirect but it uses javascript to alter the URL.

**Comment by Janglinator** [comment]
That's what I needed to hear, thank you!

I'll read a little into redirect techniques before committing to the branch, I'm not super familiar with them

**Comment by Janglinator** [comment]
This is waiting on PR #93

**Comment by kasketis** [comment]
Hi guys,
Thanks for your input so far :) After some basic tests I don't see any redirect-related issue with the current implementation (with 3xx). I'm sure that the fix (https://github.com/kasketis/netfox/pull/98) solves some issue but first I need to clarify what the issue is, before making any changes in the core. So please @2ank3th , @T-Pham , @fdematos provide as more details as possible (preferably code) in order to investigate it further. 👍

**Comment by Janglinator** [comment]
Absolutely.  I wasn’t confident on exactly what the issue is, which is why I didn’t pull it in.

**Comment by T-Pham** [comment]
I encountered the problem while on the OAuth2 process. The problem occurred when the UIWebView tried to open the first page on the AuthZ server. I cannot share the page here though.
@2ank3th encountered the problem on a 3rd-party payment gateway.
Hopefully this gives you an idea on the kind of websites where the problem happens on.

**Comment by pj4533** [comment]
I am seeing this issue with v1.11.1 while doing an OAuth2 process in my app....some sort of redirect issue.   I just commented out netfox for now and only turn it on after authentication.

**Comment by Janglinator** [comment]
Bummer!

Is there any chance you could update again (version 1.12.1 is the latest), and try again?

If that doesn't work, would you be able to give a little more info about how I could go about reproducing this issue?  Libraries used, etc?

Thanks!

**Comment by vGubriienko** [comment]
Closed due to inactivity.
