### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by scottdelly** [kasketis/netfox#63]
Would love to see this update to Swift 3.0 to begin testing soon :)

**Comment by jmurff** [comment]
I am submitting Pull Request for this as I just did it this week.

**Comment by rmato** [comment]
Nothing happened? is there a Swift 3 implementation?

**Comment by SiNBizkit** [comment]
Any news about Swift3 version?

**Comment by mcfedr** [comment]
Seems to be a more up to date pull request as https://github.com/kasketis/netfox/pull/75

For completeness, ill also link to https://github.com/kasketis/netfox/pull/73

Also a now out of date version is https://github.com/kasketis/netfox/pull/74

Would be great to see a new version released

**Comment by kasketis** [comment]
https://github.com/kasketis/netfox/tree/swift3  👍
