### ISSUE TITLE
Crash in NFXProtocol's startLoading()

### ISSUE THREAD

**Issue by smartcat32** [kasketis/netfox#64]
Even with the latest changes to Netfox, there still remains a rare crash in NFXProtocol's startLoading(), during client.URLProtocolDidFinishLoading(self).

EXC_BREAKPOINT (code=1, subcode=0x1815e97d0)

Call stack of crash:
Thread 10Queue : NSOperationQueue 0x12effa0a0 :: NSOperation 0x1300bf730 (QOS: LEGACY) (serial)
#0  0x00000001815e97d0 in _os_lock_corruption_abort ()
#1  0x00000001815e97d0 in _OSSpinLockLockSlow$VARIANT$wfe ()
#2  0x0000000181f7b570 in CFURLProtocol_NS::forgetProtocolClient() ()
#3  0x000000010019f038 in NFXProtocol.(startLoading() -> ()).(closure #1) at .../netfox/netfox/NFXProtocol.swift:89

It appears others doing NSURLProtocol work have this exact same crash.  See this: https://forums.developer.apple.com/thread/26081

And see the threading rules mentioned in that discussion thread here: https://developer.apple.com/library/ios/samplecode/CustomHTTPProtocol/Listings/Read_Me_About_CustomHTTPProtocol_txt.html

Maybe someone with more experience with Netfox's code can research and fix this? I receive reports of this crash routinely via Crashlytics, and I just hit it again in a local build I was debugging today upon launch of my app, which is using current root source of netfox (6/15/16).

**Comment by andr-ggn** [comment]
Any progress, guys?

**Comment by smartcat32** [comment]
Not that I've heard. I'm re-integrating to latest Netfox and will see if it shows up again.

**Comment by mtet88** [comment]
Any news?

**Comment by Janglinator** [comment]
Is this still an issue?  I'd like to tackle some easier bugs before reading into this.

**Comment by Abeansits** [comment]
Yes this is still an issue for us. :/

**Comment by felipeflorencio** [comment]
Can you guys verify with the last version, we had other issues similar, so would be great have a feedback about

**Comment by vGubriienko** [comment]
Close this issue because of absent activity. You may reopen it if encounter the issue.
