### ISSUE TITLE
SSL pinning support

### ISSUE THREAD

**Issue by Hardenn** [kasketis/netfox#69]
Hello, I think it'll be very useful to have an ability to use netfox with server with SSL pinning. Nowadays many apps avoid security issues, so they have pinning switched on connected server.

Any thoughts?

**Comment by vburojevic** [comment]
Any news on this or an idea how to start with implementation?

**Comment by Janglinator** [comment]
Do you experience any issues when using SSL pinning?  Pinning is done at the request level, not the protocol level, so there shouldn't actually be any issues.

**Comment by Janglinator** [comment]
This should be good to go, I'll release a new version.  Fixed in fb1e48d2b3d7720757de23bc095a9577a70d8b84
