### ISSUE TITLE
Issue with Carthage

### ISSUE THREAD

**Issue by buscarini** [kasketis/netfox#71]
I'm trying to use this with Carthage, but it doesn't work for me. I'm only building for iOS with:
`carthage build --platform iOS`

The issue is that the framework is defined as netfox_ios instead of netfox (and the same for the module name). Is there any way to make the framework and module name be "netfox" as with Cocoapods?

**Comment by Abeansits** [comment]
What is the actual error or issue here?

**Comment by Janglinator** [comment]
I haven't used Carthage in ages.  I'll get back up to speed on it one of these days and tet this out.

**Comment by Janglinator** [comment]
`carthage build --platform iOS` doesn't pull the repos included in the cartfile, it just rebuilds them.  You need to do a `carthage update` first, which builds both iOS and macOS anyways, making `carthage build --platform iOS` redundant
