### ISSUE TITLE
Alternatives.

### ISSUE THREAD

**Issue by gbrhaz** [kasketis/netfox#76]
It seems the developer for this project has gone AWOL. Does anyone have an alternative? Or has someone taken over active development on a fork somewhere?

**Comment by kasketis** [comment]
https://github.com/kasketis/netfox/tree/swift3

**Comment by Janglinator** [comment]
@gbrhaz I'm planning to work on this project within the next few weeks, I hope to make it relevant again!  It's saved us a lot of dev time in debugging, and it'd be great to keep it up to date.
