### ISSUE TITLE
Is there any way to prevent netfox grabbing all request in my app ? 

### ISSUE THREAD

**Issue by hoangpx** [kasketis/netfox#78]
I know netfox works base on NSURLProtocol. So the question is Is there any way to make a request without using NSURLProtocol  ?

**Comment by Janglinator** [comment]
```
NFX.sharedInstance().ignoreURL("the_url")
```
You can use the url of the host (for example "https://www.github.com") to ignore all paths of it.

Is this what you're looking for?

**Comment by Janglinator** [comment]
Since we don't have a reply, closing this issue.

Disabling Netfox (using `stop`) will unregister it from NSUrlProtocol.  However if Netfox is causing an issue, hence why we would want to disable it, then it sounds like we need to fix the problem rather than putting on a bandage  :)
