### ISSUE TITLE
No longer supported

### ISSUE THREAD

**Issue by Janglinator** [kasketis/netfox#80]
My coworkers and myself LOVE Netfox.  However the last commit was made 4 months ago.  I'd love to support it, is there any way I may have write access?

Thanks!

**Comment by kasketis** [comment]
Hi @Janglinator and thanks for your interest! :) What kind of support do you want to provide?

**Comment by Janglinator** [comment]
It's a nightmare simply trying to use this repository in general.  The main trunk is still swift 2, which renders it useless for development (xCode requires Swift 3).  Yes, there's a Swift 3 branch, but that means extra work is required to use it with the main trunk, which also prevents future updates.  Also, it's not a sure-fire thing copy-pasting the files; I always manage to mess it up, wasting an hour trying to debug why it isn't building.

I'd love to create 2 trunks:  one named 'netfox', the other 'netfox-swift2'.  If users *really* want updates to the swift 2 version of the project, they can edit their podfile to the swift 2 version.  Regardless, by nature of repositories, we always need to keep the latest version of the project working with the latest version of the development platform.  If we choose to support older versions, users can expect to go out of their way; not the other way around.

I'd like to try and tackle a few of the issues logged in this project.  I've created quite a few cocoapods, however my workplace has a pretty strict policy on sharing; we host all our projects on private bitbucket accounts and use a private trunk.  I won't have a ton of time in the next 2 weeks (I'll be out on a business trip), but I'd love to pick away at it in my spare time.

**Comment by kasketis** [comment]
Ok, I see.

**Comment by kasketis** [comment]
Ok, I see. Although I will be always around, please let me know for major changes and additions via mail. You are in ;)

**Comment by Janglinator** [comment]
Neat!  I won't let you down.  It might take a week or two, but I'd like to make this project kick-butt.  It's saved a lot of debugging hours, and I think more people would love it too if they knew about it.

**Comment by Abeansits** [comment]
You're amazing @Janglinator for doing this!
Let me know if there is anything I can do to help. I also love this tool and would have to see it decay.
