### ISSUE TITLE
Request body is empty

### ISSUE THREAD

**Issue by ivampir** [kasketis/netfox#84]
On the request details screen, request body is empty, but it filled in URLRequest.httpBody

**Comment by kasketis** [comment]
Could you please provide more info (steps to reproduce, etc) ?

**Comment by Janglinator** [comment]
I'm guessing this is from not using:

```
if let bodyData = mutableURLRequest.HTTPBody {
    NSURLProtocol.setProperty(bodyData, forKey: "NFXBodyData", inRequest: mutableURLRequest)
}
```

**Comment by a-promise** [comment]
In xcode 9, the func canonicalRequest(forReq:) return the request , don't have httpBody.
if use
`if let bodyData = mutableURLRequest.HTTPBody {
    NSURLProtocol.setProperty(bodyData, forKey: "NFXBodyData", inRequest: mutableURLRequest)
}`

but you don't promise  the request which is func canonicalRequest(forReq:) returned  is original request.

**Comment by razvandub** [comment]
+1

**Comment by Janglinator** [comment]
This should be fixed in the latest release!
