### ISSUE TITLE
netfox UI doesnt show up

### ISSUE THREAD

**Issue by mrfarukturgut** [kasketis/netfox#85]
Hi, 

I am using netfox in my project and I have been facing weird situation. After changing the account -which is logging out and signing in again- netfox UI does not show up both in simulator and device in debug mode. After shaking again, it closes my main.storyboard and opens up my login view controller which is in another storyboard. Maybe it does not have anything with netfox but I just wanted to ask you guys, I do not know how to figure out what causes this and you know maybe you can help.  Any thougths?

**Comment by Janglinator** [comment]
All Netfox iOS does is call `presentingViewController?.present(navigationController!, animated: true, completion: nil)`

where the nav controller is Netfox's screen, and `presentingViewController` is defined as:
```
    fileprivate var presentingViewController: UIViewController?
    {
        let rootViewController = UIApplication.shared.keyWindow?.rootViewController
        return rootViewController?.presentedViewController ?? rootViewController
    }
```

If there's weird layout issues, I'd dig deeper into your view hierarchy!  Hope this helps (and sorry it's so late :S)
